name: Build TA-Lib wheel for Windows 64-bit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_amd64:
    name: Build 64-bit TA-Lib Wheel
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # This checks out your repository

      - name: Install TA-Lib C library
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          .\vcpkg\bootstrap-vcpkg.bat
          .\vcpkg\vcpkg install ta-lib:x64-windows
          .\vcpkg\vcpkg integrate install
          .\vcpkg\vcpkg list  # List installed packages for verification

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel  # Upgrade pip, setuptools, and wheel
          pip install --use-pep517 numpy Cython  # Install with PEP 517 support

      - name: List directory contents
        run: dir  # Check the current directory structure

      - name: Build TA-Lib wheel
        run: python setup.py bdist_wheel -d ./output  # Specify output directory for the wheel

      - name: Upload built wheel
        uses: actions/upload-artifact@v4
        with:
          path: ./output/*.whl  # Adjust to match your output directory
