name: Build and Extract TA-Lib

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check if TA-Lib source exists
      shell: pwsh
      run: |
        if (Test-Path ta-lib/c/src/ta_func.c) {
          echo 'TA-Lib source files already exist, skipping download.'
          echo "exists=true" >> $env:GITHUB_ENV
        } else {
          echo 'TA-Lib source files not found, proceeding to download.'
          echo "exists=false" >> $env:GITHUB_ENV
        }
    - name: Download TA-Lib source files
      if: env.exists == 'false'
      run: |
        echo "Downloading TA-Lib source files..."
        powershell -Command "Invoke-WebRequest -Uri https://sourceforge.net/projects/ta-lib/files/ta-lib/0.4.0/ta-lib-0.4.0-msvc.zip -OutFile ta-lib-src.zip"
        if (Test-Path ta-lib-src.zip) {
          echo 'TA-Lib source files downloaded successfully.'
        } else {
          Write-Error 'Error: Failed to download TA-Lib source files.'
          exit 1
      shell: pwsh

    - name: Extract TA-Lib source files
      if: env.exists == 'false'
      run: |
        echo "Extracting TA-Lib source files..."
        
        # Ensure 7z is installed and in the PATH
        $7zPath = "C:\Program Files\7-Zip\7z.exe"
        
        if (Test-Path $7zPath) {
          & $7zPath x ta-lib-src.zip -o./ta-lib-0.4.0-msvc
        } else {
          Write-Error '7z is not installed or not found in the specified location.'
          exit 1
        }
        
        # Check if extraction was successful
        if (Test-Path ./ta-lib-0.4.0-msvc) {
          echo 'TA-Lib source files extracted successfully.'
        } else {
          Write-Error 'Error: Failed to extract TA-Lib source files.'
          exit 1
      shell: pwsh

    - name: Move TA-Lib files
      if: env.exists == 'false'
      run: |
        echo "Moving TA-Lib files to the correct location..."
        Move-Item ta-lib-0.4.0-msvc/* ta-lib/c/src
        echo 'TA-Lib files moved to ta-lib/c/src.'
      shell: pwsh

    - name: Final check
      run: |
        if (Test-Path ta-lib/c/src/ta_func.c) {
          echo 'TA-Lib setup completed successfully.'
        } else {
          Write-Error 'Error: TA-Lib setup failed.'
          exit 1
      shell: pwsh
