name: Install TA-Lib

on: 
  push:
    branches:
      - main

jobs:
  install-ta-lib:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Change to your desired Python version

      - name: Install TA-Lib
        run: |
          pip install numpy  # TA-Lib requires numpy
          pip install TA-Lib

      - name: Verify installation
        run: |
          python -c "import talib; print(talib.__version__)"
