name: Build 64-bit TA-Lib Wheel for Latest Python on Windows 10

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_64bit_wheel:
    name: Build 64-bit Wheel
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.11']  # You can adjust to the latest version of Python you're using
    env:
      VS_PLATFORM: x64  # Target 64-bit architecture
    steps:
      # Step 1: Check out the repository
      - uses: actions/checkout@v4
      
      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Ensure correct file paths and structures
      - name: Verify and prepare file structure
        run: |
          # Check for TA-Lib C source files
          if not exist ta-lib\c\src (
              echo "TA-Lib C source files not found. Aborting."
              exit 1
          )
          echo "TA-Lib C source files found."

          # Ensure proper directory structure for build
          mkdir -p ta-lib\build
          mkdir -p ta-lib\dist
          echo "Directory structure verified and prepared."

      # Step 4: Install necessary dependencies for building
      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel numpy Cython  # Ensure required tools are installed
          pip install pytest  # For running tests (optional)

      # Step 5: Build the TA-Lib wheel
      - name: Build TA-Lib Wheel
        run: |
          # Ensure correct library paths for Windows and MSBuild environment
          set LIB="ta-lib\\c\\ide\\vs2022\\lib_proj\\x64;$LIB"
          
          # Build the TA-Lib wheel
          python setup.py bdist_wheel

      # Step 6: Upload the built wheel as an artifact
      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.whl
          name: ta-lib-64bit-wheel
