Run: |
  if (Test-Path ta-lib/c/src/ta_func.c) {
    echo 'TA-Lib source files already exist, skipping download.'
    echo "exists=true" >> $env:GITHUB_ENV
  } else {
    echo 'TA-Lib source files not found, proceeding to download.'
    echo "exists=false" >> $env:GITHUB_ENV
  }
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
env:
  VS_PLATFORM: x64
  pythonLocation: C:\hostedtoolcache\windows\Python\3.11.9\x64
